### ISSUE TITLE
Meadow: route Works top level navigation route to a search stub page for works.

### ISSUE THREAD

**Issue by adamjarling** [nulib/meadow#373]
### Description
@davidschober mentioned that when clicking on "Works" top level navigation, instead of a listing of all works in the system (as currently is in place), user should be directed to a search page from which to search Works.

The data is not yet in Elasticsearch, but for now maybe just revise the Works screen to stub out what content might look like?   Or possibly provide some basic title search matching against a GraphQL query exposing works?

### Done looks like
- When clicking Works in sidenav, the resulting screen looks like what this screen will eventually become.  Functionality doesn't have to be wired up yet.

**Comment by davidschober** [comment]
I think we can remove the works link and just have a blank search retrieve all works.

Sent from my iPhone

On Dec 12, 2019, at 2:52 PM, Adam J. Arling <notifications@github.com> wrote:

﻿
Description

@davidschober<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_davidschober&d=DwMCaQ&c=yHlS04HhBraes5BQ9ueu5zKhE7rtNXt_d012z2PA6ws&r=CoXnIwMRqWuZYP2-A0a5W0Zx7oTmsndVTaITZQwG-gg&m=UIjZNUICUwe-dgYmMoNQLPcOYALGnjvjCZ0ntDLrprE&s=zuJ5FJQgj-5KXmwH3fjiiyT_Dztk_SJ0G5z8M9ol5nA&e=> mentioned that when clicking on "Works" top level navigation, instead of a listing of all works in the system (as currently is in place), user should be directed to a search page from which to search Works.

The data is not yet in Elasticsearch, but for now maybe just revise the Works screen to stub out what content might look like? Or possibly provide some basic title search matching against a GraphQL query exposing works?

Done looks like

  *   When clicking Works in sidenav, the resulting screen looks like what this screen will eventually become. Functionality doesn't have to be wired up yet.
